# Generated by Django 6.0.2 on 2026-02-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=30)),
                ("user_mail", models.EmailField(max_length=254, unique=True)),
                ("user_phone", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=128)),
                ("reg_timestamp", models.DateTimeField(auto_now_add=True)),
                ("isAdmin", models.BooleanField(default=False)),
            ],
        ),
    ]
